export enum TAGS {
  CLASSES = 'CLASSES',
  TEACHERS = 'TEACHERS',
  CLASS_DETAILS = 'CLASS_DETAILS',
  STUDENTS = 'STUDENTS',
  CLASSROOMS = 'CLASSROOMS',
  PAYMENT_DETAILS = 'PAYMENT_DETAILS',
  PAYMENTS = 'PAYMENTS',
}
