export const QK = {
  AUTH: 'AUTH',
  CLASSES: 'CLASSES',
  TEACHERS: 'TEACHERS',
  STUDENTS: 'STUDENTS',
  CLASSROOMS: 'CLASSROOMS',
  PAYMENT_DETAILS: 'PAYMENT_DETAILS',
  PAYMENTS: 'PAYMENTS',
} as const;
