export const QK = {
  AUTH: 'AUTH',
  CLASS: 'CLASS',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
  CLASSROOM: 'CLASSROOM',
  PAYMENT_DETAILS: 'PAYMENT_DETAILS',
  PAYMENT: 'PAYMENT',
  NOTICE: 'NOTICE',
  SUBJECTS: 'SUBJECTS',
} as const;
