export const QK = {
  ADMINS: 'admins',
  AUTH: 'auth',
  CLASS: 'class',
  TEACHER: 'teacher',
  STUDENT: 'student',
  CLASSROOM: 'classroom',
  PAYMENT_DETAILS: 'payment-details',
  PAYMENT: 'payment',
  NOTICE: 'notice',
  HOLIDAY: 'holiday',
  EXAM: 'exam',
  ATTENDANCE: 'attendance',
  META_DATA: 'meta-data',
  SUBJECTS: 'subjects',
  CLASSROOM_MATERIALS: 'classroom-materials',
} as const;
